### ISSUE TITLE
Update @storybook/addons peer dependency

### ISSUE THREAD

**Issue by Undistraction** [ticketmaster/storybook-styled-components#13]
The latest version has the following `peerDependency`:
```
"@storybook/addons": "^3.3.0",
```

This is a very old version. The current version at time of writing is: `5.2.1`.

Please update the dependency or use a less restrictive range.

**Comment by martynhoyer** [comment]
We've actually stopped using this in favour of: 
https://github.com/echoulen/storybook-addon-styled-component-theme

Which works much better with V5 of Storybook. We had a bunch of issues with this addon and V5 so stopped using it.

I've added a note to the readme.
