### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kristian-puccio** [ticketmaster/storybook-styled-components#2]
It seems like there have been a lot of commits since the last version was released.

Is it possible to push out the new version to npm?

**Comment by taddei** [comment]
sorry for the delay, published under 1.1.0

**Comment by kristian-puccio** [comment]
Awesome thanks for that

**Comment by Lange** [comment]
@taddei Could you publish another release? I know this library is now deprecated, but it for some reason works for me in places where the suggested replacement does not, so I still depend on it and the newly merged fix for ejected view.
